"use client"
import { Inter } from "next/font/google";
import "../app/page.module.css";
import "../styles/global.scss";
import BannerTool from "@/components/homepage/banner-tool";
import { useEffect, useState } from "react";
import Navbar from '@/components/layouts/navbar'
import { usePathname } from "next/navigation";
import { AuthUserProvider } from "@/context/authUserContext";

import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/layouts/footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const pathName = usePathname().includes('/authentication');

  let [banner, showDiscountBanner] = useState(false);

  function getUserStastics() {
    let timeStamp = JSON.parse(localStorage.getItem('offer-discount-banner'));
    if (timeStamp) {
      let currentTime = new Date();
      let sixHoursLater = new Date(timeStamp + 6 * 60 * 60 * 1000);
      if (currentTime >= sixHoursLater) {
        showDiscountBanner(true);
      } else {
        showDiscountBanner(false);
      }
    } else {
      showDiscountBanner(true);
    }
  }

  useEffect(() => {
    getUserStastics();
  }, [])

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthUserProvider>
          {
            !pathName ?
              <>
                {
                  banner ? <BannerTool showDiscountBanner={showDiscountBanner} /> : null
                }
                <Navbar />
                {children}
                <ToastContainer />
                <Footer />
              </>
              :
              <>
                {children}
                <ToastContainer />
              </>
          }
        </AuthUserProvider>
      </body>
    </html>
  );
}
